<?php

/**
* Display help and module information
* @param path which path of the site we're displaying help
* @param arg array that holds the current path as would be returned from arg() function
* @return help text for the path
*/
function brands_help($path, $arg) {
  $output = '';
  switch ($path) {
    case "admin/help#brands":
      $output = '<p>'.  t("Manages user uploaded logos and links for brands sold by LA-Di-DA") .'</p>';
      break;
  }
  return $output;
}

/**
 * Implimentation of hook_perm
 *
 * @return array
 */
function brands_perm() {
	return array('add brand logo', 'edit brand logo', 'delete brand logo');
}

/**
 * Manage user access to various 'Brands' operations
 */
function _brands_access($op, $account) {
  switch ($op) {
    case 'add':
      return user_access('add brand', $account);
    case 'edit':
      return user_access('edit brand', $account);
    case 'delete':
      return user_access('delete brand', $account);
    case 'access':
    	return user_access('access brand', $account) || user_access('edit brand logo', $account) || user_access('add brand logo', $account);
  }
}

/**
 * Implimentation of hook_theme().
 */
function brands_theme(){
	return array(
		'brands_manage' => array(
			'template' => 'brands-manage',
			'arguments' => array('xml_obj' => NULL),
	  ),
	  'brands_display' => array(
	  	'template' => 'brands-display',
	  ),
	);
}

/**
 * Implementation of hook_menu().
 */
function brands_menu() {
	global $user;
	
	$items['brands'] = array(
		'title' => 'Brands',
		'page callback' => 'brands_page',
		'access_function'	=> '_brands_access',
    'access arguments' => array('view',$user),
		'type' => MENU_CALLBACK,
    'file' => 'brands.pages.inc',
	);
	
  $items['admin/content/brands'] = array(
    'title' => 'Brands',
    'page callback' => 'brands_admin_page',
    'access_function'	=> '_brands_access',
    'access arguments' => array('delete',$user),
    'type' => MENU_CALLBACK,
    'file' => 'brands.pages.inc',
  );
  $items['admin/content/brands/delete/%'] = array(
    'title' => 'Delete Brand',
    'page callback' => 'brands_del_confirm_page',
    'access_function'	=> '_brands_access',
    'access arguments' => array('access',$user),
    'page arguments' => array(4),
    'type' => MENU_CALLBACK,
    'file' => 'brands.pages.inc',
  );
  
  return $items;
}

function _brand_addform(){
	$form['#attributes'] = array('enctype' => "multipart/form-data");
	$form['add']	= array(
		'#type'					=> 'fieldset',
		'#title'				=> 'Add a Brand',
		'#collapsible'	=> TRUE,
  	'#collapsed' 		=> FALSE,
	);
	$form['add']['name'] = array(
		'#type'				=> 'textfield',
		'#title'			=> 'Brand name',
		'#maxlength'	=> 128,
		'#required'		=> true,
	);
	$form['add']['link'] = array(
		'#type'				=> 'textfield',
		'#title'			=> 'Brand website',
		'#description'=> 'ex. http:\\www.brand.com',
		'#maxlength'	=> 255,
		'#required'		=> false,
	);
	$form['add']['logo'] = array(
		'#type'				=> 'file',
		'#title'			=> 'Logo',
		'#required'		=> false,
	);
	$form['add']['submit'] = array(
		'#type'				=> 'submit',
		'#value'			=> t('Add Brand')
	);
	return $form;
}

function _brand_addform_submit($form, &$form_state) {
	$upload = file_save_upload('logo', array(), 'files/brands/', false);
	
	$xml_file = variable_get('brands_xml_file',$_SERVER['DOCUMENT_ROOT'].'/'.file_directory_path().'/brands/brands.xml');
	$xml_obj = @simplexml_load_file($xml_file);
	
	$brand = $xml_obj->addChild('brand',$form['add']['name']['#value']);
	$brand->addAttribute('href',$form['add']['link']['#value']);
	$brand->addAttribute('src','/'.$upload->destination);
	
	$file = fopen($xml_file,'w');
	fwrite($file,$xml_obj->asXML());
	fclose($file);
}

