<?php

/**
* Display help and module information
* @param path which path of the site we're displaying help
* @param arg array that holds the current path as would be returned from arg() function
* @return help text for the path
*/
function x_help($path, $arg) {
  $output = '';
  switch ($path) {
    case "admin/help#x":
      $output = '<p>'.  t("Handles content for the site") .'</p>';
      break;
  }
  return $output;
} 

/**
 * Implementation of hook_menu().
 */
function x_menu(){
	$items['contact'] = array(
    'title' => 'Contact Us',
    'page callback' => 'x_contact_page',
    'type' => MENU_CALLBACK,
    'access callback' => '_x_contact_access',
    'file' => 'x.pages.inc',
  );
  
  return $items;
}

function _x_contact_access(){
	return true;
}

/**
 * Implimentation of hook_mail()
 *
 * @param string $key which mail message that this mod is responsible for are we sending
 * @param array $message settings needed to send this message
 * @param array $params extra info needed to send message
 */
function x_mail($key, &$message, $params){
	switch($key) {
		case 'contact':
		$message['subject'] = t('Message from a ladidaladida.com user');
		$message['body'] = t($params['name']." says: ".$params['msg']);
		break;
	}
}

/****************************** 
 *       FORM HANDLING 
 *****************************/
function _x_contactform(){	
	$form['name'] = array(
		'#type'				=> 'textfield',
		'#title'			=> 'Your name',
		'#maxlength'	=> 128,
		'#required'		=> true,
	);
	$form['email'] = array(
		'#type'		=> 'textfield',
		'#title'	=> 'Your email address',
		'#required'		=> true,
	);
	$form['message'] = array(
		'#type'		=> 'textarea',
		'#title'	=> 'Message',
	);
	$form['send'] = array(
	  '#type' 	=> 'submit',
	  '#value'	=> t('Send'),
	);
	
	return($form);
}
function _x_contactform_submit($form){
	$to = variable_get('site_mail','ladida707@comcast.net');
	
	drupal_mail('x','contact',$to,language_default(),array('msg'=>$form['message']['#value'],'name'=>$form['name']['#value']),$form['email']['#value']);
	
	drupal_set_message('Your message has been sent to La-Di-Da.');
}